### PR TITLE
multiprocessed download, progress bar, better resume

### PR DESCRIPTION
**Pull request by dreamflasher**
* add requirements.txt
* add multiprocessing download capability
* save download file list after listing bucket, load if it exists to speed up resume
* add progress bar to see current and remaining time, speed of download etc.

### CODE REVIEW

**Comment by Ucnt** [comment]
You are awesome.  Thanks!

**Comment by Ucnt** [comment]
Had to make a couple of tweaks to the download_bucket_public.py file, e.g. removing utf-8 encodings, tweaking how the keys are added with truncated results, and doing url encoding.

Let me know if those don't work well for you after a pull of new code.

**Comment by dreamflasher** [comment]
I removed the url encoding and some of the encoding stuff because it didn't work on my machine (Ubuntu 18.04). Don't really know what's the best solution there, encoding is generally a mess…

**Comment by Ucnt** [comment]
I'll add it back in a try/catch.

**Comment by Ucnt** [comment]
Or rather...you said .encode("utf-8") did NOT work on your box?  If so,
then the current version should.

Def let me know.   Otherwise I a try/except is, while not pretty, a working
solution.

**Comment by dreamflasher** [comment]
Yeah, let me rerun the code after a pull and I'll create a ticket if I have any troubles! :) Thank you!

**Comment by Ucnt** [comment]
Cool.   Ran on a test bucket I use "msven-public" and it worked well.

**Pull request merged**
